### ISSUE TITLE
Solver.py - Checking gamma

### ISSUE THREAD

**Issue by Anselmoo** [NSLS-II/edrixs#37]
This will crash if `len(gamma_c) < len(n_om)`  and the same for `len(gamma_f) < len(n_eloss)`

    if np.isscalar(gamma_c):
        gamma_core[:] = np.ones(n_om) * gamma_c
    else:
        gamma_core[:] = gamma_c

_A possible solution:_

    if np.isscalar(gamma_c):
        gamma_core[:] = np.ones(n_om) * gamma_c
    else:
        if len(gamma_c) != n_om:
            gamma_core[:] = np.ones(n_om) * gamma_c[0]
        else:
            gamma_core[:] = gamma_c

**Comment by mpmdean** [comment]
I think this would be a case where the user has not followed the docstring, which says that the gamma_c should be a scalar or an array with the same size as n_om.

So I think it's best that EDRIXS throws an error here otherwise the code is probably doing something unanticipated. The error created will be of the type:
ValueError                                Traceback (most recent call last)
```
<ipython-input-5-dcbd839566c1> in <module>
----> 1 gamma_core[:] = gamma_c

ValueError: could not broadcast input array from shape (1,2) into shape (1,3)
```
I tend to think this is sufficiently clear? @Anselmoo pleases let me know what you think.

If not, we can catch the error and thow a more descriptive error. 
try:
    gamma_core[:] = gamma_c
except ValueError:
    raise Exception("The spaces of gamma_c and ominc of {} and {} are incomatible.".format(gamma_c, 
    ominc))

**Comment by mpmdean** [comment]
@Anselmoo are you happy with my reply? I'm presuming you are since you did not reply. I'll close this issue for now on this basis and will reopen if needed.

**Comment by Anselmoo** [comment]
Of course Mark!
Thx, I think you make a great job and don’t wanna disturb you. I am also not so familiar with the GitHub community.
Thank you very much and have a greet week.

Anselm

On 4. Sep 2019, at 16:28, Mark <notifications@github.com<mailto:notifications@github.com>> wrote:


@Anselmoo<https://github.com/Anselmoo> are you happy with my reply? I'm presuming you are since you did not reply. I'll close this issue for now on this basis and will reopen if needed.

**Comment by mpmdean** [comment]
We're always happy to discuss ideas for changes so thank you.
